Lint line endings in the dataset.

diff --git a/.github/workflows/validator.yml b/.github/workflows/validator.yml
--- a/.github/workflows/validator.yml
+++ b/.github/workflows/validator.yml
@@ -12,10 +12,36 @@ jobs:
 
     steps:
 
-    - name: Set up Python
-      uses: actions/setup-python@v2
+    - name: Checkout
+      uses: actions/checkout@v2
       with:
-        python-version: 3.7
+        # make sure to download directly from the PR's repo, whether that is this repo or a fork
+        # By default github generates a merge commit for each PR in this repo, but only for the one branch under test
+        # but `git-annex` needs access to *two* branches: the current branch and `git-annex`
+        # this might be subtly buggy since it is testing the remote version, not the merged version
+        #
+        # *if* this is not a pull request, this will fall back to its default behaviour.
+        repository: ${{github.event.pull_request.head.repo.full_name}}
+        ref: ${{ github.event.pull_request.head.ref }}
+
+    - name: Install dos2unix
+      run: |
+        # the easy way to do this: convert everything to unix and ask git if that changed anything
+        sudo apt-get install -y dos2unix
+
+    - name: Check line endings
+      run: |
+        # the easy way to do this: convert everything to unix and ask git if that changed anything
+
+        find ./ -path ./.git -prune -o -type f -print0 | xargs -0 dos2unix -q
+        # this version is safer, but more maintenance:
+        #find ./ -path ./.git -prune -o -type f \( ! -name "*.nii" -a ! -name "*.nii.gz" \) -print0 | xargs -0 dos2unix -q
+
+        git diff --stat --exit-code
+        if [ "$?" -ne 0 ]; then
+          echo "error: Windows line endings found."
+          exit 1
+        fi
 
     #- name: Update software
     #  run: |
@@ -36,6 +62,11 @@ jobs:
         sudo apt-get install -y nodejs
         sudo npm install -g bids-validator
 
+    - name: Set up Python
+      uses: actions/setup-python@v2
+      with:
+        python-version: 3.7
+
     - name: Install spine-generic for acquisition parameters check
       run: pip install spinegeneric@git+https://github.com/spine-generic/spine-generic.git@master
 
@@ -46,18 +77,6 @@ jobs:
     #    # try enabling this.
     #    # ref: https://github.com/actions/virtual-environments/issues/2606#issuecomment-772683150
     #    sudo rm -rf /usr/local/lib/android /usr/share/dotnet
-
-    - name: Checkout
-      uses: actions/checkout@v2
-      with:
-        # make sure to download directly from the PR's repo, whether that is this repo or a fork
-        # By default github generates a merge commit for each PR in this repo, but only for the one branch under test
-        # but `git-annex` needs access to *two* branches: the current branch and `git-annex`
-        # this might be subtly buggy since it is testing the remote version, not the merged version
-        #
-        # *if* this is not a pull request, this will fall back to its default behaviour.
-        repository: ${{github.event.pull_request.head.repo.full_name}}
-        ref: ${{ github.event.pull_request.head.ref }}
 
     - name: git config
       run: |
