Revamp github actions validation workflow (#180)
* Switch from nodejs to deno for bids-validator

* Simplify workflows which don't depend on git-annex

* Don't update all apt packages

The current github runner images already reference a
recent-enough version of git-annex, so there's no need.

* Consolidate git-annex configuration

Also, there's no real need to set `annex.alwayscommit`
to `false`, so let's stay closer to the default config.

`git annex init` is implicitly run by `git annex get`.

* Reinstate spine-generic validator output

* Show warnings instead of failing the validation on error

* Synchronize with data-single-subject

diff --git a/.github/workflows/validator.yml b/.github/workflows/validator.yml
--- a/.github/workflows/validator.yml
+++ b/.github/workflows/validator.yml
@@ -1,5 +1,5 @@
-
 name: Dataset Validator
+
 on:
   push:
     branches: [ master ]
@@ -9,7 +9,6 @@ on:
 jobs:
   Validate:
     runs-on: ubuntu-latest
-
     steps:
 
     - name: Gain disk space by remapping temp disk (`/dev/sdb1`)
@@ -32,70 +31,50 @@ jobs:
         #
         # *if* this is not a pull request, this will fall back to its default behaviour.
         repository: ${{github.event.pull_request.head.repo.full_name}}
-        ref: ${{ github.event.pull_request.head.ref }}
-
-    - name: Update apt packages
-      run: |
-        # do we want to do this? it's helpful to avoid testing against surprise out-of-date software, but also so slow.
-        sudo apt-get update &&
-        sudo DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade &&
-        sudo DEBIAN_FRONTEND=noninteractive apt-get autoremove
+        ref: ${{github.event.pull_request.head.ref}}
 
     - name: Install git-annex
       run: |
-        sudo apt-get install -y git-annex
-        git config --global annex.thin true
-        git config --global annex.retry 2
-
-    - name: Setup NodeJS (for bids-validator)
-      uses: actions/setup-node@v4
-
-    - name: Install bids-validator
-      run: sudo npm install -g bids-validator
-
-    - name: Set up Python
-      uses: actions/setup-python@v5
-      with:
-        python-version: 3.11
-
-    - name: Install spine-generic for acquisition parameters check
-      run: pip install spinegeneric@git+https://github.com/spine-generic/spine-generic.git@master
-
-    - name: git config
-      run: |
-        # this is needed by git-annex so that it can write to the local git-annex branch
-        # the tracking information about the local copy
+        sudo apt-get update
+        sudo apt-get --yes install git-annex
+        # the user name and email is needed by git-annex to write to
+        # the local git-annex branch
         git config --global user.name "gh-actions"
         git config --global user.email "gh-actions"
-        # but actually, disable those writes. We don't need them because we're throwing away this copy immediately.
-        # this might make the previous two lines unnecessary, but it's safer just to leave them both in
-        git config annex.alwayscommit false
+        # save space by using hard links to annexed files
+        git config --global annex.thin true
+        # retry for transient failures when downloading annexed file contents
+        git config --global annex.retry 2
 
     - name: Download dataset
       run: |
-        git fetch --depth=1 origin git-annex:git-annex # actions/checkout@v4 does a shallow checkout, so it is missing this important branch
-        git annex init
-        git annex get -J8
+        git fetch --depth=1 origin git-annex:git-annex
+        git annex get --jobs 8
 
-    - name: Checking BIDS compliance
-      if: always()
-      run: |
-        bids-validator --verbose ./ | tee bids.txt
-        printf "\nShort summary:\n\n"
-        # FIXME: This should be replaced with bids-validator settings: A) throw error on warning or B) warning ignores
-        ! grep "\[WARN\]\|\[ERR\]" bids.txt  # ! -> Reverse error code so "found == error thrown"
+    - name: Install Deno
+      uses: denoland/setup-deno@v2
 
-    - name: Checking acquisition parameters
-      if: always()
-      run: |
-        sg_params_checker -path-in ./ | tee params.txt
-        # FIXME: Checking the output like this should be replaced with SG throwing actual errors
-        ! grep "WARNING" params.txt  # ! -> Reverse error code so "found == error thrown"
+    - name: Install Python 3.13
+      uses: actions/setup-python@v5
+      with:
+        python-version: 3.13
 
-    - name: Checking data consistency
-      if: always()
+    - name: Install spine-generic
       run: |
-        sg_check_data_consistency -path-in ./ | tee consistency.txt
-        # FIXME: Checking the output like this should be replaced with SG throwing actual errors
-        ! grep "Warning\|Missing" consistency.txt
-        grep "all good" consistency.txt
+        pip install spinegeneric@git+https://github.com/spine-generic/spine-generic.git@v2.9
+
+    - name: Run bids-validator
+      # If the explicit whitelist of allowed environment variables gets too annoying to update,
+      # we can loosen it to just a blanket `--allow-env`. This will let bids-validator and all of its
+      # dependencies access any credentials that github CI exposes in environment variables, but at
+      # least we're not giving it any network access, so exfiltrating them would require more effort.
+      run: |
+        deno run --no-prompt --allow-env=BIDS_SCHEMA,FORCE_COLOR,IGNORE_TEST_WIN32 --allow-read=. jsr:@bids/validator . || echo '::warning title=bids-validator::Errors found by bids-validator'
+
+    - name: Run acquisition parameter validator
+      run: |
+        sg_params_checker -path-in . || echo '::warning title=bids-validator::Errors found by sg_params_checker'
+
+    - name: Run data consistency validator
+      run: |
+        sg_check_data_consistency -path-in . || echo '::warning title=bids-validator::Errors found by sg_check_data_consistency'
